const Map<String, String> fi ={
  "begateway_form_hint_card_number": "Kortin numero",
  "begateway_form_hint_expiration": "Päättymispäivä",
  "begateway_form_hint_cardholder_name": "Kortinhaltijan nimi",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Kuukausi",
  "begateway_year": "Vuosi",
  "begateway_card_number_required": "Kortin numero vaaditaan",
  "begateway_card_number_invalid": "Kortin numero ei kelpaa",
  "begateway_cvv_required": "CVV/CVC vaaditaan",
  "begateway_cvv_invalid": "CVV/CVC ei kelpaa",
  "begateway_expiration_required": "Päättymispäivä vaaditaan",
  "begateway_expiration_invalid": "Päättymispäivä ei kelpaa",
  "begateway_cardholder_name_required": "Nimi kortissa vaaditaan",
  "begateway_savecard": "Muista seuraavalla kerralla",
  "begateway_button_pay": "Maksa",
  "begateway_secure_info": "Turvallisen maksun tarjoaa",
  "change": "Vaihda",
  "sorry_incorrect_data": "Maksussa tapahtui virhe. Yritä uudelleen tai käytä toista korttia.",
  "ok": "OK",
  "cancel": "Peruuta",
  "turn_on": "Käytä",
  "error": "Virhe",
  "an_error_occurred_during_scanning": "Skannaamisen aikana tapahtui virhe",
  "please_turn_on_nfc": "Ota NFC käyttöön",
  "nfc_not_supported": "NFC:tä ei tueta",
  "please_attach_bank_card_to_the_phone": "Liitä pankkikortti puhelimeen",
  "from_photo": "Skannaa kameralla",
  "scan_by_nfc": "Skannaa NFC:llä",
  "please_wait": "Odota",
  "back": "Takaisin",
  "or_use_a_card": "tai käytä korttia",
  "please_scan_your_card": "Skannaa korttisi",
  "another_card": "Toinen kortti",
  "want_delete_card": "Haluatko todella poistaa tämän pankkikortin?"
};
