const Map<String, String> lv ={
  "begateway_form_hint_card_number": "Kartes numurs",
  "begateway_form_hint_expiration": "Derīguma termiņš",
  "begateway_form_hint_cardholder_name": "Vārds, uzvārds uz kartes",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Mēnesis",
  "begateway_year": "Gads",
  "begateway_card_number_required": "Obligāti jānorāda kartes numurs",
  "begateway_card_number_invalid": "Kartes numurs nav derīgs",
  "begateway_cvv_required": "CVV/CVC ir obligāti aizpildāmais lauks",
  "begateway_cvv_invalid": "CVV/CVC nav derīgs",
  "begateway_expiration_required": "Derīguma termiņš jānorāda obligāti",
  "begateway_expiration_invalid": "Derīguma termiņš nav derīgs",
  "begateway_cardholder_name_required": "Vārds, uzvārds uz kartes jānorāda obligāti",
  "begateway_savecard": "Saglabāt karti",
  "begateway_button_pay": "Maksāt",
  "begateway_secure_info": "Drošo pakalpojumu nodrošina",
  "change": "Mainīt",
  "sorry_incorrect_data": "Radās maksājuma kļūda. Mēģiniet vēlreiz vai izmantojiet citu karti.",
  "ok": "Labi",
  "cancel": "Atcelt",
  "turn_on": "Ieslēgt",
  "error": "Kļūda",
  "an_error_occurred_during_scanning": "Skenēšanas laikā radās kļūda",
  "please_turn_on_nfc": "Ieslēdziet NFC",
  "nfc_not_supported": "NFC tehnoloģija netiek atbalstīta",
  "please_attach_bank_card_to_the_phone": "Pielieciet bankas karti pie tālruņa",
  "from_photo": "Noskenējiet ar kameru",
  "scan_by_nfc": "Noskenējiet ar NFC",
  "please_wait": "Lūdzu, uzgaidiet",
  "back": "Atpakaļ",
  "or_use_a_card": "vai arī izmantojiet karti",
  "please_scan_your_card": "Lūdzu, skenējiet savu karti",
  "another_card": "Cita karte",
  "want_delete_card": "Vai tiešām vēlaties noņemt šo bankas karti?"
};
