const Map<String, String> nb ={
  "begateway_form_hint_card_number": "Kortnummer",
  "begateway_form_hint_expiration": "Utløpsdato",
  "begateway_form_hint_cardholder_name": "Navn på kort",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Måned",
  "begateway_year": "År",
  "begateway_card_number_required": "Kortnummer er nødvendig",
  "begateway_card_number_invalid": "Kortnummer er ugyldig",
  "begateway_cvv_required": "CVV/CVC er nødvendig",
  "begateway_cvv_invalid": "CVV/CVC er ugyldig",
  "begateway_expiration_required": "Utløpsdato er nødvendig",
  "begateway_expiration_invalid": "Utløpsdato er ugyldig",
  "begateway_cardholder_name_required": "Navn på kort er nødvendig",
  "begateway_savecard": "Lagre kortet",
  "begateway_button_pay": "Betal",
  "begateway_secure_info": "Sikker betaling tilbys av",
  "change": "Endre",
  "sorry_incorrect_data": "En betalingsfeil oppsto. Prøv igjen eller prøv et annet kort.",
  "ok": "OK",
  "cancel": "Avbryt",
  "turn_on": "Slå på",
  "error": "Feil",
  "an_error_occurred_during_scanning": "En feil oppstod under skanning",
  "please_turn_on_nfc": "Slå på NFC",
  "nfc_not_supported": "NFC støttes ikke",
  "please_attach_bank_card_to_the_phone": "Legg til bankkort til telefonen",
  "from_photo": "Skann med kamera",
  "scan_by_nfc": "Skann med NFC",
  "please_wait": "Vennligst vent",
  "back": "Tilbake",
  "or_use_a_card": "eller bruk kort",
  "please_scan_your_card": "Vennligst skann kortet ditt",
  "another_card": "Et annet kort",
  "want_delete_card": "Vil du virkelig slette dette bankkortet?"
};
