const Map<String, String> da ={
  "begateway_form_hint_card_number": "Kortnummer",
  "begateway_form_hint_expiration": "Udløbsdato",
  "begateway_form_hint_cardholder_name": "Kortholder navn",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Måned",
  "begateway_year": "År",
  "begateway_card_number_required": "Kortnummeret er obligatorisk",
  "begateway_card_number_invalid": "Kortnummeret er ugyldigt",
  "begateway_cvv_required": "CVV/CVC er obligatorisk",
  "begateway_cvv_invalid": "CVV/CVC er ugyldig",
  "begateway_expiration_required": "Udløbsdatoen er obligatorisk",
  "begateway_expiration_invalid": "Udløbsdatoen er ugyldig",
  "begateway_cardholder_name_required": "Navnet på kortet er obligatorisk",
  "begateway_savecard": "Husk mig næste gang",
  "begateway_button_pay": "Betal",
  "begateway_secure_info": "Sikker betaling leveres af",
  "change": "Ændring",
  "sorry_incorrect_data": "Der var en betalingsfejl.Prøv igen eller brug et andet kort.",
  "ok": "OK",
  "cancel": "Annuller",
  "turn_on": "Aktivér",
  "error": "Fejl",
  "an_error_occurred_during_scanning": "Der opstod en fejl under scanning",
  "please_turn_on_nfc": "Aktivér NFC",
  "nfc_not_supported": "NFC er ikke understøttet",
  "please_attach_bank_card_to_the_phone": "Vedhæft bankkortet til telefonen",
  "from_photo": "Scan med kamera",
  "scan_by_nfc": "Scan med NFC",
  "please_wait": "Vent venligst",
  "back": "Tilbage",
  "or_use_a_card": "eller brug et kort",
  "please_scan_your_card": "Scan dit kort",
  "another_card": "Et andet kort",
  "want_delete_card": "Vil du virkelig slette dette bankkort?"
};
