const Map<String, String> ka ={
  "begateway_form_hint_card_number": "ბარათის ნომერი",
  "begateway_form_hint_expiration": "ვადის გასვლის თარიღი",
  "begateway_form_hint_cardholder_name": "სახელი ბარათზე",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "თვე",
  "begateway_year": "წელი",
  "begateway_card_number_required": "საჭიროა ბარათის ნომერი",
  "begateway_card_number_invalid": "ბარათის ნომერი არასწორია",
  "begateway_cvv_required": "CVV/CVC აუცილებელია",
  "begateway_cvv_invalid": "CVV/CVC არასწორია",
  "begateway_expiration_required": "აუცილებელია ვადის გასვლის თარიღის მითითება",
  "begateway_expiration_invalid": "ვადის გასვლის თარიღი არასწორია",
  "begateway_cardholder_name_required": "ბარათზე დატანილი სახელის მითითება აუცილებელია",
  "begateway_savecard": "ბარათის შენახვა",
  "begateway_button_pay": "გადახდა",
  "begateway_secure_info": "უსაფრთხო გადახდა გარანტირებულია",
  "change": "შეცვლა",
  "sorry_incorrect_data": "მოხდა გადახდის შეცდომა. გთხოვთ ცადეთ განმეორებით ან გამოიყენეთ სხვა ბარათი.",
  "ok": "კარგი",
  "cancel": "გაუქმება",
  "turn_on": "ჩართვა",
  "error": "შეცდომა",
  "an_error_occurred_during_scanning": "სკანირებისას გამოვლინდა შეცდომა",
  "please_turn_on_nfc": "გთხოვთ ჩართეთ NFC",
  "nfc_not_supported": "NFC არ არის მხარდაჭერილი",
  "please_attach_bank_card_to_the_phone": "გთხოვთ ტელეფონს დაუკავშირეთ თქვენი საბანკო ბარათი",
  "from_photo": "კამერის სკანირება",
  "scan_by_nfc": "სკანირება NFC-ით",
  "please_wait": "გთხოვთ დაელოდეთ",
  "back": "უკან",
  "or_use_a_card": "ან გამოიყენეთ ბარათი",
  "please_scan_your_card": "გთხოვთ, დაასკანიროთ თქვენი ბარათი",
  "another_card": "კიდევ ერთი ბარათი",
  "want_delete_card": "ნამდვილად გსურთ ამ საბანკო ბარათის წაშლა?"
};
