const Map<String, String> zh ={
  "begateway_form_hint_card_number": "卡号",
  "begateway_form_hint_expiration": "到期日期",
  "begateway_form_hint_cardholder_name": "持卡人姓名",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "月",
  "begateway_year": "年",
  "begateway_card_number_required": "卡号为必填项",
  "begateway_card_number_invalid": "卡号无效",
  "begateway_cvv_required": "CVV/CVC 为必填项",
  "begateway_cvv_invalid": "CVV/CVC 无效",
  "begateway_expiration_required": "到期日期为必填项",
  "begateway_expiration_invalid": "到期日期无效",
  "begateway_cardholder_name_required": "卡片上的名字为必填项",
  "begateway_savecard": "下次记住我",
  "begateway_button_pay": "支付",
  "begateway_secure_info": "安全付款提供方",
  "change": "更改",
  "sorry_incorrect_data": "付款出错。重试或使用另一张卡。",
  "ok": "确定",
  "cancel": "取消",
  "turn_on": "打开",
  "error": "错误",
  "an_error_occurred_during_scanning": "扫描过程中发生错误",
  "please_turn_on_nfc": "请开启 NFC",
  "nfc_not_supported": "不支持 NFC",
  "please_attach_bank_card_to_the_phone": "请将银行卡紧贴手机",
  "from_photo": "用摄像头扫描",
  "scan_by_nfc": "用 NFC 扫描",
  "please_wait": "请稍等",
  "back": "返回",
  "or_use_a_card": "或使用卡片",
  "please_scan_your_card": "请扫描您的卡",
  "another_card": "另一张卡",
  "want_delete_card": "你真的想删除这张银行卡吗?"
};
