const Map<String, String> ru ={
  "begateway_form_hint_card_number": "Номер карты",
  "begateway_form_hint_expiration": "Срок действия",
  "begateway_form_hint_cardholder_name": "Имя на карте",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Месяц",
  "begateway_year": "Год",
  "begateway_card_number_required": "Необходимо указать номер карты",
  "begateway_card_number_invalid": "Неверный номер карты",
  "begateway_cvv_required": "Необходимо указать СVV/СVC",
  "begateway_cvv_invalid": "СVV/СVC неверный",
  "begateway_expiration_required": "Необходимо указать срок действия",
  "begateway_expiration_invalid": "Срок действия недействительный",
  "begateway_cardholder_name_required": "Необходимо указать имя, написанное на карте",
  "begateway_savecard": "Запомнить карту",
  "begateway_button_pay": "Оплатить",
  "begateway_secure_info": "Безопасная оплата обеспечивается",
  "change": "Изменить",
  "sorry_incorrect_data": "Ошибка в процессе оплаты. Попробуйте еще раз или используйте другую карту",
  "ok": "OK",
  "cancel": "Отменить",
  "turn_on": "Включить",
  "error": "Ошибка",
  "an_error_occurred_during_scanning": "При сканировании произошла ошибка",
  "please_turn_on_nfc": "Включите NFC",
  "nfc_not_supported": "NFC не поддерживается",
  "please_attach_bank_card_to_the_phone": "Приложите банковскую карту к телефону",
  "from_photo": "Сканировать камерой",
  "scan_by_nfc": "Сканировать через NFC",
  "please_wait": "Ожидайте",
  "back": "Назад",
  "or_use_a_card": "или используйте карту",
  "please_scan_your_card": "Пожалуйста, отсканируйте свою карточку",
  "another_card": "Другая карта",
  "want_delete_card": "Вы действительно хотите удалить эту банковскую карту?"
};

