const Map<String, String> tr ={
  "begateway_form_hint_card_number": "Kart numarası",
  "begateway_form_hint_expiration": "Son kullanma tarihi",
  "begateway_form_hint_cardholder_name": "Kart üzerindeki isim",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Ay",
  "begateway_year": "Yıl",
  "begateway_card_number_required": "Kart numarası gerekli",
  "begateway_card_number_invalid": "Kart numarası geçersiz",
  "begateway_cvv_required": "CVV/CVC gerekli",
  "begateway_cvv_invalid": "CVV/CVC geçersiz",
  "begateway_expiration_required": "Son kullanma tarihi gerekli",
  "begateway_expiration_invalid": "Son kullanma tarihi geçersiz",
  "begateway_cardholder_name_required": "Kart üzerindeki isim gerekli",
  "begateway_savecard": "Sonraki sefere beni hatırla",
  "begateway_button_pay": "Öde",
  "begateway_secure_info": "Güvenli ödeme sağlayıcısı",
  "change": "Değiştir",
  "sorry_incorrect_data": "Ödeme hatası. Tekrar deneyin veya başka bir kart kullanın.",
  "ok": "Tamam",
  "cancel": "İptal",
  "turn_on": "Aç",
  "error": "Hata",
  "an_error_occurred_during_scanning": "Tarama sırasında bir hata oluştu",
  "please_turn_on_nfc": "Lütfen NFC'yi açın",
  "nfc_not_supported": "NFC desteklenmiyor",
  "please_attach_bank_card_to_the_phone": "Lütfen banka kartını telefona ekleyin",
  "from_photo": "Kamerayla tara",
  "scan_by_nfc": "NFC ile tara",
  "please_wait": "Lütfen bekleyin",
  "back": "Geri",
  "or_use_a_card": "veya kartı kullanın",
  "please_scan_your_card": "Lütfen kartınızı tarayın",
  "another_card": "Diğer harita",
  "want_delete_card": "Bu banka kartını gerçekten silmek istiyor musunuz?"
};
