const Map<String, String> ja ={
  "begateway_form_hint_card_number": "カード番号",
  "begateway_form_hint_expiration": "有効期限",
  "begateway_form_hint_cardholder_name": "カードの名義",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "月",
  "begateway_year": "年",
  "begateway_card_number_required": "カード番号は必須です",
  "begateway_card_number_invalid": "カード番号は無効です",
  "begateway_cvv_required": "CVV/CVC は必須です",
  "begateway_cvv_invalid": "CVV/CVC は無効です",
  "begateway_expiration_required": "有効期限は必須です",
  "begateway_expiration_invalid": "有効期限は無効です",
  "begateway_cardholder_name_required": "カード名義人は必須です",
  "begateway_savecard": "次回もこれを使用する",
  "begateway_button_pay": "支払う",
  "begateway_secure_info": "セキュア決済の提供元",
  "change": "変更",
  "sorry_incorrect_data": "お支払いにエラーがありました。再試行するか、別のカードを使用してください。",
  "ok": "OK",
  "cancel": "キャンセル",
  "turn_on": "オンにする",
  "error": "エラー",
  "an_error_occurred_during_scanning": "スキャン中にエラーが発生しました",
  "please_turn_on_nfc": "NFCをオンにしてください",
  "nfc_not_supported": "NFCはサポートされていません",
  "please_attach_bank_card_to_the_phone": "電話に銀行カードを添付してください",
  "from_photo": "カメラでスキャンする",
  "scan_by_nfc": "NFCでスキャンする",
  "please_wait": "お待ちください",
  "back": "戻る",
  "or_use_a_card": "またはカードを使用します",
  "please_scan_your_card": "カードをスキャンしてください",
  "another_card": "別のカード",
  "want_delete_card": "あなたは本当にこの銀行カードを削除しますか？"
};
