
const Map<String, String> az = {
  "begateway_form_hint_card_number": "Kartı nömrəsi",
  "begateway_form_hint_expiration": "Son istifadə tarixi",
  "begateway_form_hint_cardholder_name": "Kart üzərindəki ad",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Ay",
  "begateway_year": "İlİl",
  "begateway_card_number_required": "Kart nömrəsi tələb olunur",
  "begateway_card_number_invalid": "Kart nömrəsi yanlışdır",
  "begateway_cvv_required": "CVV/CVC tələb olunur",
  "begateway_cvv_invalid": "CVV/CVC yanlışdır",
  "begateway_expiration_required": "Son istifadə tarixi tələb olunur",
  "begateway_expiration_invalid": "Son istifadə tarixi etibarsızdır",
  "begateway_cardholder_name_required": "Kartdakı ad tələb olunur",
  "begateway_savecard": "Kartı saxla",
  "begateway_button_pay": "Ödəyin",
  "begateway_secure_info": "Təhlükəsiz ödəniş tərəfindən təmin edilir",
  "change": "Dəyişin",
  "sorry_incorrect_data": "Ödəniş xətası baş verdi. Yenidən cəhd edin və ya başqa kartdan istifadə edin.",
  "ok": "Oldu",
  "cancel": "Ləğv et!",
  "turn_on": "İşə sal",
  "error": "Xəta",
  "an_error_occurred_during_scanning": "Skanlama zamanı xəta baş verdi",
  "please_turn_on_nfc": "Lütfən NFC qoşun",
  "nfc_not_supported": "NFC dəstəklənmir",
  "please_attach_bank_card_to_the_phone": "Lütfən bank kartı telefona qoşun",
  "from_photo": "Kamera ilə skanlayın",
  "scan_by_nfc": "NFC ilə skanlayın",
  "please_wait": "Lütfən gözləyin",
  "back": "Geri",
  "or_use_a_card": "və ya kartdan istifadə edin",
  "please_scan_your_card": "Zəhmət olmasa kartınızı tarayın",
  "another_card": "Digər kart",
  "want_delete_card": "Həqiqətən bu bank kartını silmək istəyirsiniz?"
};
