const Map<String, String> uk ={
  "begateway_form_hint_card_number": "Номер картки",
  "begateway_form_hint_expiration": "Термін дії",
  "begateway_form_hint_cardholder_name": "Ім'я на картці",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Місяць",
  "begateway_year": "Рік",
  "begateway_card_number_required": "Потрібно вказати номер картки",
  "begateway_card_number_invalid": "Номер картки недійсний",
  "begateway_cvv_required": "Потрібно вказати такі дані: CVV/CVC",
  "begateway_cvv_invalid": "Ці дані недійсні: CVV/CVC",
  "begateway_expiration_required": "Потрібно вказати термін дії",
  "begateway_expiration_invalid": "Термін дії недійсний",
  "begateway_cardholder_name_required": "Потрібно вказати ім’я на картці",
  "begateway_savecard": "Зберегти картку",
  "begateway_button_pay": "Сплатити",
  "begateway_secure_info": "Захищений платіж забезпечує",
  "change": "Змінити",
  "sorry_incorrect_data": "Під час оплати сталася помилка. Спробуйте ще раз або скористайтеся іншою карткою.",
  "ok": "OK",
  "cancel": "Скасувати",
  "turn_on": "Увімкнути",
  "error": "Помилка",
  "an_error_occurred_during_scanning": "Під час сканування сталася помилка",
  "please_turn_on_nfc": "Увімкніть NFC",
  "nfc_not_supported": "NFC не підтримується",
  "please_attach_bank_card_to_the_phone": "Прикладіть банківську картку до телефона",
  "from_photo": "Проскануйте камерою",
  "scan_by_nfc": "Сканувати модулем NFC",
  "please_wait": "Зачекайте",
  "back": "Назад",
  "or_use_a_card": "або використовуйте карту",
  "please_scan_your_card": "Будь ласка, відскануйте свою картку",
  "another_card": "Інша карта",
  "want_delete_card": "Ви дійсно хочете видалити цю банківську картку?"
};
