 const Map<String, String> en ={
  "dismissPresentation": "Tap to Dismiss Presentation.",
  "changeSizeOfPresentation": "Tap to switch between presentation sizes.",
  "begateway_form_hint_card_number": "Card number",
  "begateway_form_hint_expiration": "Expiration date",
  "begateway_form_hint_cardholder_name": "Name on card",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Month",
  "begateway_year": "Year",
  "begateway_card_number_required": "Card number is required",
  "begateway_card_number_invalid": "Card number is invalid",
  "begateway_cvv_required": "CVV/CVC is required",
  "begateway_cvv_invalid": "CVV/CVC is invalid",
  "begateway_expiration_required": "Expiration date is required",
  "begateway_expiration_invalid": "Expiration date is invalid",
  "begateway_cardholder_name_required": "Name on card is required",
  "begateway_savecard": "Save card",
  "begateway_secure_info": "Secure payment is provided by",
  "begateway_button_pay": "Pay",
  "cancel": "Cancel",
  "change": "Change",
  "scan_by_camera": "Scan by camera",
  "sorry_incorrect_data": "There was a payment error. Try again or use another card.",
  "ok": "OK",
  "turn_on": "Turn on",
  "error": "Error",
  "an_error_occurred_during_scanning": "An error occurred during scanning",
  "please_turn_on_nfc": "Please turn on NFC",
  "nfc_not_supported": "NFC not supported",
  "please_attach_bank_card_to_the_phone": "Please attach bank card to the phone",
  "from_photo": "Scan by camera",
  "scan_by_nfc": "Scan by NFC",
  "please_wait": "Please wait",
  "card_validation_failed": "Card validation failed",
  "cvc_validation_failed": "CVC code validation failed",
  "name_validation_failed": "Name validation failed",
  "date_validation_failed": "Date validation failed",
  "back": "Back",
  "or_use_a_card": "or use a card",
  "please_scan_your_card": "Please scan your card",
  "another_card": "Another card",
  "want_delete_card": "Do you really want to delete this bank card?"
};

