const Map<String, String> sv ={
  "begateway_form_hint_card_number": "Kortnummer",
  "begateway_form_hint_expiration": "Förfallodatum",
  "begateway_form_hint_cardholder_name": "Namn på kortet",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Månad",
  "begateway_year": "År",
  "begateway_card_number_required": "Kortnummer krävs",
  "begateway_card_number_invalid": "Kortnumret är ogiltigt",
  "begateway_cvv_required": "CVV/CVC krävs",
  "begateway_cvv_invalid": "CVV/CVC är ogiltig",
  "begateway_expiration_required": "Förfallodatum krävs",
  "begateway_expiration_invalid": "Förfallodatum är ogiltigt",
  "begateway_cardholder_name_required": "Namn på kortet krävs",
  "begateway_savecard": "Kom ihåg mig nästa gång",
  "begateway_button_pay": "Betala",
  "begateway_secure_info": "Säker betalning tillhandahålls av",
  "change": "Ändra",
  "sorry_incorrect_data": "Ett betalningsfel har inträffat. Försök igen eller använd ett annat kort.",
  "ok": "OK",
  "cancel": "Avbryt",
  "turn_on": "Slå på",
  "error": "Fel",
  "an_error_occurred_during_scanning": "Ett fel inträffade vid skanning",
  "please_turn_on_nfc": "Slå på NFC",
  "nfc_not_supported": "NFC stöds inte",
  "please_attach_bank_card_to_the_phone": "Bifoga bankkort till telefonen",
  "from_photo": "Skanna med kamera",
  "scan_by_nfc": "Skanna med NFC",
  "please_wait": "Vänta",
  "back": "Tillbaka",
  "or_use_a_card": "eller använd ett kort",
  "please_scan_your_card": "Skanna ditt kort",
  "another_card": "Ett annat kort",
  "want_delete_card": "Vill du verkligen ta bort detta bankkort?"
};
