const Map<String, String> de ={
  "begateway_form_hint_card_number": "Kartennummer",
  "begateway_form_hint_expiration": "Ablaufdatum",
  "begateway_form_hint_cardholder_name": "Name auf der Karte",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Monat",
  "begateway_year": "Jahr",
  "begateway_card_number_required": "Kartennummer ist erforderlich",
  "begateway_card_number_invalid": "Kartennummer ist ungültig",
  "begateway_cvv_required": "CVV/CVC ist erforderlich",
  "begateway_cvv_invalid": "CVV/CVC ist ungültig",
  "begateway_expiration_required": "Ablaufdatum ist erforderlich",
  "begateway_expiration_invalid": "Ablaufdatum ist ungültig",
  "begateway_cardholder_name_required": "Name auf der Karte ist erforderlich",
  "begateway_savecard": "Meine Daten merken",
  "begateway_button_pay": "Bezahlen",
  "begateway_secure_info": "Sichere Zahlungsmethode wird angeboten von",
  "change": "Ändern",
  "sorry_incorrect_data": "Es ist ein Zahlungsfehler aufgetreten. Versuchen Sie es erneut oder verwenden Sie eine andere Karte.",
  "ok": "OK",
  "cancel": "Abbrechen",
  "turn_on": "Einschalten",
  "error": "Fehler",
  "an_error_occurred_during_scanning": "Beim Scannen ist ein Fehler aufgetreten",
  "please_turn_on_nfc": "Bitte schalte NFC ein",
  "nfc_not_supported": "NFC wird nicht unterstützt",
  "please_attach_bank_card_to_the_phone": "Bitte Bankkarte dem Telefon zuführen",
  "from_photo": "Mit der Kamera scannen",
  "scan_by_nfc": "Per NFC scannen",
  "please_wait": "Bitte warten",
  "back": "Zurück",
  "or_use_a_card": "oder verwenden Sie eine Karte",
  "please_scan_your_card": "Bitte scannen Sie Ihre Karte",
  "another_card": "Andere Karte",
  "want_delete_card": "Möchten Sie diese Bankkarte wirklich löschen?"
};
