const Map<String, String> ro ={
  "begateway_form_hint_card_number": "Număr card",
  "begateway_form_hint_expiration": "Data expirării",
  "begateway_form_hint_cardholder_name": "Numele de pe card",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Lună",
  "begateway_year": "An",
  "begateway_card_number_required": "Numărul cardului este necesar",
  "begateway_card_number_invalid": "Numărul cardului este invalid",
  "begateway_cvv_required": "CVV/CVC este necesar",
  "begateway_cvv_invalid": "CVV/CVC este invalid",
  "begateway_expiration_required": "Data expirării este obligatorie",
  "begateway_expiration_invalid": "Data expirării este invalidă",
  "begateway_cardholder_name_required": "Numele de pe card este necesar",
  "begateway_savecard": "Salvați cardul",
  "begateway_button_pay": "Plătiți",
  "begateway_secure_info": "Plata securizată este oferită de",
  "change": "Schimbare",
  "sorry_incorrect_data": "A apărut o eroare de plată. Încercați din nou sau utilizați un alt card.",
  "ok": "OK",
  "cancel": "Anulare",
  "turn_on": "Pornire",
  "error": "Eroare",
  "an_error_occurred_during_scanning": "A apărut o eroare în timpul scanării",
  "please_turn_on_nfc": "Activați NFC",
  "nfc_not_supported": "NFC nu este acceptat",
  "please_attach_bank_card_to_the_phone": "Vă rugăm să atașați cardul bancar la telefon",
  "from_photo": "Scanați prin cameră",
  "scan_by_nfc": "Scanați prin NFC",
  "please_wait": "Vă rugăm să așteptați",
  "back": "Înapoi",
  "or_use_a_card": "sau folosiți un card",
  "please_scan_your_card": "Vă rugăm să scanați cardul",
  "another_card": "O altă carte",
  "want_delete_card": "Chiar doriți să ștergeți acest card bancar?"
};
