const Map<String, String> be = {
  "begateway_form_hint_card_number": "Нумар карткі",
  "begateway_form_hint_expiration": "Тэрмін дзеяння",
  "begateway_form_hint_cardholder_name": "Імя на картцы",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Месяц",
  "begateway_year": "Год",
  "begateway_card_number_required": "Неабходна ўказаць нумар карты",
  "begateway_card_number_invalid": "Нумар карты несапраўдны",
  "begateway_cvv_required": "Неабходна ўказаць CVV/CVC",
  "begateway_cvv_invalid": "CVV/CVC несапраўдны",
  "begateway_expiration_required": "Неабходна ўказаць тэрмін дзеяння",
  "begateway_expiration_invalid": "Тэрмін дзеяння несапраўдны",
  "begateway_cardholder_name_required": "Неабходна ўказаць імя, напісанае на карце",
  "begateway_savecard": "Запомніць картку",
  "begateway_button_pay": "Аплаціць",
  "begateway_secure_info": "Абароненыя плацяжы на платформе",
  "change": "Змяніць",
  "sorry_incorrect_data": "Памылка аплаты. Паўтарыце спробу або выкарыстайце іншую картку",
  "ok": "OK",
  "cancel": "Скасаваць",
  "turn_on": "Уключыць",
  "error": "Памылка",
  "an_error_occurred_during_scanning": "Пры сканіраванні адбылася памылка",
  "please_turn_on_nfc": "Уключыце NFC",
  "nfc_not_supported": "NFC не падтрымліваецца",
  "please_attach_bank_card_to_the_phone": "Прыкладзіце банкаўскую карту да тэлефона",
  "from_photo": "Сканіраванне камерай",
  "scan_by_nfc": "Сканіраванне праз NFC",
  "please_wait": "Чакайце",
  "back": "Назад",
  "or_use_a_card": "або выкарыстоўвайце карту",
  "please_scan_your_card": "Калі ласка, отсканируйте сваю картку",
  "another_card": "Іншая карта",
  "want_delete_card": "Вы сапраўды хочаце выдаліць гэтую банкаўскую карту?"
};
