const Map<String, String> pl ={
  "begateway_form_hint_card_number": "Numer karty",
  "begateway_form_hint_expiration": "Data ważności",
  "begateway_form_hint_cardholder_name": "Nazwisko na karcie",
  "begateway_cvv": "CVV",
  "begateway_cvc": "CVC",
  "begateway_cid": "CID",
  "begateway_cvn": "CVN",
  "begateway_month": "Miesiąc",
  "begateway_year": "Rok",
  "begateway_card_number_required": "Numer karty jest wymagany",
  "begateway_card_number_invalid": "Numer karty jest nieprawidłowy",
  "begateway_cvv_required": "Kod CVV/CVC jest wymagany",
  "begateway_cvv_invalid": "Kod CVV/CVC jest nieprawidłowy",
  "begateway_expiration_required": "Data ważności jest wymagana",
  "begateway_expiration_invalid": "Data ważności jest nieprawidłowa",
  "begateway_cardholder_name_required": "Imię i nazwisko na karcie są wymagane",
  "begateway_savecard": "Pamiętaj mnie następnym razem",
  "begateway_button_pay": "Zapłać",
  "begateway_secure_info": "Bezpieczną płatność zapewnCVV/CVC",
  "change": "Zmień",
  "sorry_incorrect_data": "Wystąpił błąd płatności. Spróbuj ponownie lub użyj innej karty.",
  "ok": "OK",
  "cancel": "Anuluj",
  "turn_on": "Włącz",
  "error": "Błąd",
  "an_error_occurred_during_scanning": "Podczas skanowania wystąpił błąd",
  "please_turn_on_nfc": "Włącz NFC",
  "nfc_not_supported": "Brak obsługi NFC",
  "please_attach_bank_card_to_the_phone": "Podłącz kartę bankową do telefonu",
  "from_photo": "Skanuj kamerą",
  "scan_by_nfc": "Skanuj przez NFC",
  "please_wait": "Czekaj",
  "back": "Do tyłu",
  "or_use_a_card": "lub użyj mapy",
  "please_scan_your_card": "Zeskanuj swoją kartę",
  "another_card": "Inną Mapa",
  "want_delete_card": "Czy naprawdę chcesz usunąć tę kartę bankową?"
};
